### ISSUE TITLE
Zmiana http response na poprawną

### ISSUE THREAD

**Issue by WiktorSzymanski** [WiktorSzymanski/JSON_tools_IO#21]
W AdviceController.java zwracany jest HTTP response CONFLICT, gdy bardziej odzwierciedlającym rzeczywisty status jest BAD_REQUEST.

https://github.com/WiktorSzymanski/JSON_tools_IO/blob/712670e7262a62e16e1651bead72a1df4162e0d5/src/main/java/pl/put/poznan/JSON_tools/rest/AdviceController.java#L22

**Comment by BartoszDolata** [comment]
Logged time 10min

**Comment by WiktorSzymanski** [comment]
Logged time 10min
