### ISSUE TITLE
Zrobić dokumentację

### ISSUE THREAD

**Issue by WiktorSzymanski** [WiktorSzymanski/JSON_tools_IO#36]
Dokumentacja kodu (http://www.oracle.com/technetwork/articles/java/index-137868.html)

Dokumentacja generuje się w sposób automatyczny podczas budowy oprogramowania.
 * Przynajmniej 1 klasa / interfejs posiada pełną dokumentację techniczną* (javadoc, itp.)
 * Przynajmniej 3 klasy / interfejsy posiadają pełną dokumentację techniczną* (javadoc, itp.)

**Comment by BartoszDolata** [comment]
Dokumentacja stworzona dla 5 klas.

Brak automatycznego generowania podczas budowania oprogramowania

**Comment by BartoszDolata** [comment]
Automatycznego generowania podczas budowania oprogramowania dodane

**Comment by BartoszDolata** [comment]
Logged time 2h

**Comment by WiktorSzymanski** [comment]
Logged time 20m
